In [23]:
a=True
b=False
c=a and b
d=a or b

for i in range(10) :
    print("1234","hfapiuf",";ahf;ah", sep='   trfdsfdg')
help(print)


1234   trfdsfdghfapiuf   trfdsfdg;ahf;ah
1234   trfdsfdghfapiuf   trfdsfdg;ahf;ah
1234   trfdsfdghfapiuf   trfdsfdg;ahf;ah
1234   trfdsfdghfapiuf   trfdsfdg;ahf;ah
1234   trfdsfdghfapiuf   trfdsfdg;ahf;ah
1234   trfdsfdghfapiuf   trfdsfdg;ahf;ah
1234   trfdsfdghfapiuf   trfdsfdg;ahf;ah
1234   trfdsfdghfapiuf   trfdsfdg;ahf;ah
1234   trfdsfdghfapiuf   trfdsfdg;ahf;ah
1234   trfdsfdghfapiuf   trfdsfdg;ahf;ah
Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [ ]:
age=(input("enter age")).lower()

if "male"==age:
    print("MALE")
elif "female"==age:
    print("Feminist")
else:
    print("Aabhash")        

Feminist


In [ ]:

c=0
while c==0:
    x,y=map(int,input("Enter two numbers:").split(','))
    operation=input("Enter the operation to be performed:").upper()
    match operation:
        case "ADD":
            c=0
            print("Sum=",x+y)
            
        case "SUB":
            c=0
            print("Sub=",x-y)
        case "PROD":
            c=0
            print("Prod=",x*y)
        case "DIV":
            c=0
            print("Div=",round(x/y,2))
        case "MOD":
            c=0
            print("Mod=",x%y)
        case _:
            c=1
            print("Invalid Input")
    


Mod= 23
Invalid Input


In [93]:
#LIST
a=('1','2','3',7482,5)


print(a[::-1])

(5, 7482, '3', '2', '1')


In [ ]:
#DICTIONARY
dict={}
for i in range(20):
    dict={i:i**2}
print

    



In [109]:
help(print)

Help on dict object:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |
 |  Built-in subclasses:
 |      StgDict
 |
 |  Methods defined here:
 |
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __init

In [30]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])


print(b)
print(b.shape)
print(b.ndim)
print(b.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9


In [33]:
c=b.reshape(1,9)
print(c)

[[1 2 3 4 5 6 7 8 9]]


In [ ]:
d=np.arange(1,10)
print(d)

[1 2 3 4 5 6 7 8 9]


In [38]:
d=np.linspace(1,8,9)
print(d)

[1.    1.875 2.75  3.625 4.5   5.375 6.25  7.125 8.   ]


In [48]:
ones=np.ones(4)
print(ones)
d=np.arange(1,5)
d + ones

[1. 1. 1. 1.]


array([2., 3., 4., 5.])